### PR TITLE
Fixed #69: Fixed integration tests

### LINKED ISSUE #69: Fix integration tests
### Task specification

The `api/private/test/process/...` endpoint is no longer available, mocks are approving automatically.

### PR DESCRIPTION
**Pull request by kober32**
Fixed #69

- integration tests are now expecting auto-approval for the approval state

### CODE REVIEW

File: library/src/androidTest/java/com/wultra/android/digitalonboarding/IntegrationTests.kt [hunk 1]
```diff
@@ -100,8 +102,9 @@ class IntegrationTests {
     fun fullOnboardingFlow() {
         // We test as far as we can until we hit environment mocking limits.
         runForAllEnvironments { env, helper ->
+            val label = processLabel(helper)
```
Comment (marek-ch) [inline library/src/androidTest/java/com/wultra/android/digitalonboarding/IntegrationTests.kt:105]: `label` -> `processId` ? To be in sync with iOS and also more explicit

**Review by marek-ch — APPROVED** [review]

File: library/src/androidTest/java/com/wultra/android/digitalonboarding/IntegrationTests.kt (hunk 1 above)
Comment (kober32) [reply library/src/androidTest/java/com/wultra/android/digitalonboarding/IntegrationTests.kt:105]: Yea, I did it little bit different (so it's added already formatted) but I think it's ok for tests...
